### ISSUE TITLE
"Failed building wheel for netsnmp-py" how can i solve this problem

### ISSUE THREAD

**Issue by kentowen** [xstaticxgpx/netsnmp-py3#10]
C:\Users\Administrator>pip install netsnmp-py
Collecting netsnmp-py
  Using cached netsnmp-py-0.2.tar.gz
Building wheels for collected packages: netsnmp-py
  Running setup.py bdist_wheel for netsnmp-py ... error
  Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;**file**='c:\users\admini~1\appdata\local\temp\pip-build-mw5toq\netsnmp-py\setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" bdist_wheel -d c:\users\admini~1\appdata\local\temp\tmpc0pvcepip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-2.7
  creating build\lib.win-amd64-2.7\netsnmp
  copying netsnmp_hex.py -> build\lib.win-amd64-2.7\netsnmp
  copying netsnmp__init__.py -> build\lib.win-amd64-2.7\netsnmp
  copying netsnmp__main__.py -> build\lib.win-amd64-2.7\netsnmp
  creating build\lib.win-amd64-2.7\netsnmp_dev
  copying netsnmp_dev\arris.py -> build\lib.win-amd64-2.7\netsnmp_dev
  copying netsnmp_dev\cisco.py -> build\lib.win-amd64-2.7\netsnmp_dev
  copying netsnmp_dev\technicolor.py -> build\lib.win-amd64-2.7\netsnmp_dev
  copying netsnmp_dev__init__.py -> build\lib.win-amd64-2.7\netsnmp_dev
  running build_ext
  building 'netsnmp._api' extension
  creating build\temp.win-amd64-2.7
  creating build\temp.win-amd64-2.7\Release
  creating build\temp.win-amd64-2.7\Release\netsnmp
  C:\Users\Administrator\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -I./netsnmp -Ic:\python27\include -Ic:\python27\PC /Tcnetsnmp/session.c /Fobuild\temp.win-amd64-2.7\Release\netsnmp/session.obj
  session.c
  ./netsnmp_api.h(1) : fatal error C1083: Cannot open include file: 'net-snmp/net-snmp-config.h': No such file or directory
  error: command 'C:\Users\Administrator\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe' failed with exit status 2

---

  Failed building wheel for netsnmp-py
  Running setup.py clean for netsnmp-py
Failed to build netsnmp-py
Installing collected packages: netsnmp-py
  Running setup.py install for netsnmp-py ... error
    Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;**file**='c:\users\admini~1\appdata\local\temp\pip-build-mw5toq\netsnmp-py\setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record c:\users\admini~1\appdata\local\temp\pip-pope26-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-2.7
    creating build\lib.win-amd64-2.7\netsnmp
    copying netsnmp_hex.py -> build\lib.win-amd64-2.7\netsnmp
    copying netsnmp__init__.py -> build\lib.win-amd64-2.7\netsnmp
    copying netsnmp__main__.py -> build\lib.win-amd64-2.7\netsnmp
    creating build\lib.win-amd64-2.7\netsnmp_dev
    copying netsnmp_dev\arris.py -> build\lib.win-amd64-2.7\netsnmp_dev
    copying netsnmp_dev\cisco.py -> build\lib.win-amd64-2.7\netsnmp_dev
    copying netsnmp_dev\technicolor.py -> build\lib.win-amd64-2.7\netsnmp_dev
    copying netsnmp_dev__init__.py -> build\lib.win-amd64-2.7\netsnmp_dev
    running build_ext
    building 'netsnmp._api' extension
    creating build\temp.win-amd64-2.7
    creating build\temp.win-amd64-2.7\Release
    creating build\temp.win-amd64-2.7\Release\netsnmp
    C:\Users\Administrator\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -I./netsnmp -Ic:\python27\include -Ic:\python27\PC /Tcnetsnmp/session.c /Fobuild\temp.win-amd64-2.7\Release\netsnmp/session.obj
    session.c
    ./netsnmp_api.h(1) : fatal error C1083: Cannot open include file: 'net-snmp/net-snmp-config.h': No such file or directory
    error: command 'C:\Users\Administrator\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe' failed with exit status 2

```
----------------------------------------
```

Command "c:\python27\python.exe -u -c "import setuptools, tokenize;**file**='c:\users\admini~1\appdata\local\temp\pip-build-mw5toq\netsnmp-py\setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record c:\users\admini~1\appdata\local\temp\pip-pope26-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\admini~1\appdata\local\temp\pip-build-mw5toq\netsnmp-py\

**Comment by xstaticxgpx** [comment]
This does not support Windows
