### ISSUE TITLE
it is window compitible?

### ISSUE THREAD

**Issue by rajjaisur** [xstaticxgpx/netsnmp-py3#15]
I was trying to install it in window 10.
and I got following error on manual installation.
================================================
D:\net-snmp-5.7.3\python>python setup.py --basedir=/Build/net-snmp-5.7.3 build_ext -i
running build_ext
building 'netsnmp.client_intf' extension
creating build
creating build\temp.win32-2.7
creating build\temp.win32-2.7\Release
creating build\temp.win32-2.7\Release\netsnmp
C:\Users\admin\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\include -IC:\Python27\PC /Tcnetsnmp/client_intf.c /Fobuild\temp.win32-2.7\Release\netsnmp/client_intf.obj
client_intf.c
C:\Python27\include\net-snmp/net-snmp-config.h(312) : warning C4005: 'HAVE_GETPID' : macro redefinition
        c:\python27\include\pyconfig.h(601) : see previous definition of 'HAVE_GETPID'
C:\Python27\include\net-snmp/net-snmp-config.h(362) : warning C4005: 'HAVE_IO_H' : macro redefinition
        c:\python27\include\pyconfig.h(58) : see previous definition of 'HAVE_IO_H'
C:\Python27\include\net-snmp/net-snmp-config.h(674) : warning C4005: 'HAVE_SNPRINTF' : macro redefinition
        c:\python27\include\pyerrors.h(315) : see previous definition of 'HAVE_SNPRINTF'
C:\Python27\include\net-snmp/net-snmp-config.h(703) : warning C4005: 'HAVE_STRERROR' : macro redefinition
        c:\python27\include\pyconfig.h(64) : see previous definition of 'HAVE_STRERROR'
C:\Python27\include\net-snmp/library/system.h(178) : error C2061: syntax error : identifier 'strtoull'
C:\Python27\include\net-snmp/library/system.h(178) : error C2059: syntax error : ';'
C:\Python27\include\net-snmp/library/system.h(178) : error C2059: syntax error : 'type'
C:\Python27\include\net-snmp/library/system.h(189) : error C2146: syntax error : missing ')' before identifier 'mode'
C:\Python27\include\net-snmp/library/system.h(189) : error C2081: 'mode_t' : name in formal parameter list illegal
C:\Python27\include\net-snmp/library/system.h(189) : error C2061: syntax error : identifier 'mode'
C:\Python27\include\net-snmp/library/system.h(189) : error C2059: syntax error : ';'
C:\Python27\include\net-snmp/library/system.h(189) : error C2059: syntax error : ','
C:\Python27\include\net-snmp/library/system.h(190) : error C2059: syntax error : ')'
netsnmp/client_intf.c(12) : fatal error C1083: Cannot open include file: 'arpa/inet.h': No such file or directory
error: command 'C:\\Users\\admin\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2
===================================================================
I am also trying to search for inet.h header file but I found that It is for Unix like system window has winsock2.h sould i replace it in client_intf.c file ??? or You have better suggestion??

**Comment by xstaticxgpx** [comment]
You are building the legacy python bindings provided with net-snmp there.
`client_intf` is a legacy module.

Clone this repo somewhere and try building with `--basedir=D:\net-snmp-5.7.3`
