### ISSUE TITLE
generators should not raise stopiteration

### ISSUE THREAD

**Issue by mweinelt** [xstaticxgpx/netsnmp-py3#16]
in https://github.com/xstaticxgpx/netsnmp-py3/blob/master/netsnmp/__init__.py#L155-L156 the generator raises a stopiteration, which is implicitly converted to a runtimeerror.

drop the raise and let the function return to cleanly exit the generator.

see https://www.python.org/dev/peps/pep-0479/.

**Comment by xstaticxgpx** [comment]
Thanks, fixed in b1c0825f50c8fdaa1f7086f2e671f1acf2578b5d

**Comment by mweinelt** [comment]
Yep, that works. Now if you could just bump the version.

**Comment by xstaticxgpx** [comment]
v0.5 released
